### ISSUE TITLE
some info missing in get_sensors_param

### ISSUE THREAD

**Issue by felixchenier** [felixchenier/NextWheel#23]
Currently, get_sensors_param returns this:

```
{'accelerometer_precision': 2,
 'gyrometer_precision': 250,
 'imu_sampling_rate': 60,
 'adc_sampling_rate': 1000}
```

power_sampling_rate and encoder_sampling_rate are missing.

**Comment by doumdi** [comment]
@felixchenier Did you build and upload the latest firmware because the field should be there: https://github.com/felixchenier/NextWheel/blob/f6cda1dcfe562afd2d26dcfc9052d98f93f9923b/firmware/arduino_esp32/src/tasks/WebSocketServerTask.cpp#L287

Also, why would you need a power_sampling_rate ?

**Comment by felixchenier** [comment]
@doumdi My bad. It is. I reverted to an old firmware to check something and I forgot to reflash the newest one. And you're right, power_sample_rate makes no sense.
