### ISSUE TITLE
NextWheel.file_list() freezes

### ISSUE THREAD

**Issue by felixchenier** [felixchenier/NextWheel#9]
```python
import nextwheel
nw = nextwheel.NextWheel(ip_address)
nw.connect()
nw.file_list()
```

freezes instead of returning the file list.

**Comment by doumdi** [comment]
/Users/dominic/miniconda3/envs/python-3.10/bin/python /Users/dominic/Documents/working_area/NextWheel/python/api_examples/file_list.py 
file_list returned code: 200 json: {'files': [{'name': 'log_2000-12-31_19-04-42.dat', 'size': 24278}], 'download_url': '/file_download', 'delete_url': '/file_delete'}
log_2000-12-31_19-04-42.dat 24278

**Comment by doumdi** [comment]
@felixchenier SDCard working / formatted ?

**Comment by felixchenier** [comment]
It works ok now. I close for now.
